### ISSUE TITLE
Make Retry button clickable to restart game. Fix Javascript issue.

### ISSUE THREAD

**Issue by prasanthLalapeta** [fidisys/hacktoberfest-html5-game#2]
Right now `Retry` button is not clickable. Looks like javascript issue. 

### **Expected Behaviour on click of `Retry` button**

<img width="570" alt="Screen Shot 2019-10-23 at 1 51 49 AM" src="https://user-images.githubusercontent.com/40259256/67328882-bb8b8480-f537-11e9-961a-6be587bcec86.png">

**Comment by zarasyversen** [comment]
I'm happy to help with this if you want @prasanthLalapeta :)

**Comment by samanthakem** [comment]
I have submitted the PR https://github.com/fidisys/hacktoberfest-html5-game/pull/6 to fix this issue. Sorry @zarasyversen, one thing I learned from Open Source is that the first PR submitted is what mostly counts, I have lost opportunities cuz I saw someone took an issue and I passed, months later the issue was still sitting around. Either way, feel free to submit another PR and the maintainer will pick the best one. Have a great day you both.

**Comment by zarasyversen** [comment]
Thanks @samanthakem :)

**Comment by samanthakem** [comment]
What do you think @prasanthLalapeta? Do you need me to do any changes?

**Comment by prasanthLalapeta** [comment]
Thanks @samanthakem 👍
